/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.usjt.elevador;

/**
 *
 * @author 824117322
 */
public class TelaElevadorteste extends javax.swing.JFrame {
    private Elevador elevador;
    
    /**
     * Creates new form NewJFrame
     */
    public TelaElevadorteste() {
        elevador = new Elevador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        elevadorSubirBotao = new javax.swing.JButton();
        elevadorDescerBotao = new javax.swing.JButton();
        EntrarGente = new javax.swing.JButton();
        SubirPessoa = new javax.swing.JButton();
        DescerPessoa = new javax.swing.JButton();
        qtdPessoasLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sentidoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        elevadorSubirBotao.setText("Subir");
        elevadorSubirBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevadorSubirBotaoActionPerformed(evt);
            }
        });

        elevadorDescerBotao.setText("Descer");
        elevadorDescerBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevadorDescerBotaoActionPerformed(evt);
            }
        });

        EntrarGente.setText("EntrarGente...");

        SubirPessoa.setText("Subir Pessoa");

        DescerPessoa.setText("Descer Pessoa");
        DescerPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescerPessoaActionPerformed(evt);
            }
        });

        qtdPessoasLabel.setText("Quantidade de Pessoas: 0");

        jLabel1.setText("Sentido do Elevador");

        sentidoLabel.setText("subindo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(elevadorSubirBotao)
                .addGap(18, 18, 18)
                .addComponent(elevadorDescerBotao)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sentidoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qtdPessoasLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EntrarGente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(SubirPessoa)
                        .addGap(28, 28, 28)
                        .addComponent(DescerPessoa)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(qtdPessoasLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sentidoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elevadorSubirBotao)
                    .addComponent(elevadorDescerBotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntrarGente)
                    .addComponent(SubirPessoa)
                    .addComponent(DescerPessoa))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescerPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescerPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescerPessoaActionPerformed

    private void elevadorSubirBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevadorSubirBotaoActionPerformed
        elevador.sobe();
        sentidoLabel.setText("subindo");
    }//GEN-LAST:event_elevadorSubirBotaoActionPerformed

    private void elevadorDescerBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevadorDescerBotaoActionPerformed
        elevador.desce();
        sentidoLabel.setText
    }//GEN-LAST:event_elevadorDescerBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaElevadorteste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaElevadorteste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaElevadorteste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaElevadorteste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaElevadorteste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DescerPessoa;
    private javax.swing.JButton EntrarGente;
    private javax.swing.JButton SubirPessoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton elevadorDescerBotao;
    private javax.swing.JButton elevadorSubirBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel qtdPessoasLabel;
    private javax.swing.JLabel sentidoLabel;
    // End of variables declaration//GEN-END:variables
}
